spring:
  datasource:
    url: jdbc:h2:mem:rotinalize;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""               # melhor que null
  jpa:
    open-in-view: false        # boa prática (evita warning)
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console